import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { operationsError, operationsDb } from './operationsApi'
import { Button } from '@/shared/ui/button'
import { Input } from '@/shared/ui/input'
export function EntityRulesEditor({entityId,editable}:{entityId:string;editable:boolean}){
 const [selected,setSelected]=useState(''),[min,setMin]=useState(''),[max,setMax]=useState(''),[length,setLength]=useState(''),[target,setTarget]=useState(''),[targetKey,setTargetKey]=useState('id'),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const attributes=useQuery({queryKey:['entity-rules',entityId],queryFn:async()=>{const {data,error}=await operationsDb.from('entity_attributes').select('id,key,validation_rules').eq('entity_id',entityId);if(error)throw operationsError(error);return data??[]}})
 async function save(){setBusy(true);setError('');try{const rules:Record<string,unknown>={};for(const [k,v] of [['min',min],['max',max],['maxLength',length]])if(v!==''){if(!Number.isFinite(Number(v)))throw new Error('Enter numeric limits');rules[k]=Number(v)}if(min!==''&&max!==''&&Number(min)>Number(max))throw new Error('Minimum cannot exceed maximum');if(length!==''&&(!Number.isInteger(Number(length))||Number(length)<0))throw new Error('Text length must be a nonnegative whole number');if(target&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(target))throw new Error('Choose a valid related entity ID');if(target){rules.referenceEntityId=target;rules.referenceAttribute=targetKey||'id'}const {error}=await operationsDb.from('entity_attributes').update({validation_rules:rules}).eq('id',selected).eq('entity_id',entityId);if(error)throw operationsError(error);await attributes.refetch()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <details className="rounded border p-3"><summary className="cursor-pointer text-sm font-semibold">Field validation and relationships</summary><p className="py-2 text-xs">Rules apply to new and updated records. Relationships reference a unique field in an entity in this organisation; referenced records cannot be deleted. Review existing data before adding a rule.</p><fieldset disabled={!editable||busy} className="space-y-2"><select aria-label="Field to validate" className="w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);const r=attributes.data?.find(a=>a.id===e.target.value)?.validation_rules??{};setMin(r.min===undefined?'':String(r.min));setMax(r.max===undefined?'':String(r.max));setLength(r.maxLength===undefined?'':String(r.maxLength));setTarget(r.referenceEntityId??'');setTargetKey(r.referenceAttribute??'id')}}><option value="">Choose field</option>{attributes.data?.map(a=><option key={a.id} value={a.id}>{a.key}</option>)}</select><div className="grid gap-2 sm:grid-cols-3"><Input type="number" aria-label="Minimum value" placeholder="Minimum number" value={min} onChange={e=>setMin(e.target.value)}/><Input type="number" aria-label="Maximum value" placeholder="Maximum number" value={max} onChange={e=>setMax(e.target.value)}/><Input type="number" min={0} step={1} aria-label="Maximum text length" placeholder="Maximum text length" value={length} onChange={e=>setLength(e.target.value)}/></div><Input aria-label="Related entity ID" placeholder="Related entity ID (optional)" value={target} onChange={e=>setTarget(e.target.value)}/><Input aria-label="Related unique field" placeholder="Related unique field" value={targetKey} onChange={e=>setTargetKey(e.target.value)}/><Button size="sm" disabled={!selected||busy} onClick={()=>void save()}>Save field rules</Button></fieldset>{error||attributes.error?<p role="alert">{error||attributes.error?.message}</p>:null}</details>
}
