import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import { TEMPLATE_KINDS, starterTemplateContent, parseTemplateContent, templateExprValue } from '../src/features/templates/templateModel'
import { defaultConfig, flowNodeTypes, questionAnswerTypes, questionConfigSchema, entityConfigSchema } from '../src/features/designer/model/flowSchema'
import { parseFlowExport } from '../src/features/designer/utils/flowTransfer'
import { parseChatSegments } from '../src/features/designer/model/chatbotMedia'
import { interpolateTemplate } from '../src/features/designer/preview/expressionEval'
import { createInitialPreviewState, tickPreview } from '../src/features/designer/preview/previewRuntime'
const dir = fileURLToPath(new URL('../../artifacts/flowforge-atlas', import.meta.url))
const path = resolve(dir, 'FlowForge-Atlas.json')
const pack = JSON.parse(readFileSync(path, 'utf8'))
if (process.env.BUILD_ATLAS === '1') {
  pack.nodes = pack.nodes.map((n: any) => ({ ...n, config: { ...defaultConfig(n.type), ...n.config } }))
  pack.templates = TEMPLATE_KINDS.map(kind => ({key:'atlas_'+kind, name:'Atlas '+kind.replaceAll('_',' '), kind, description:'Fictional showcase template. Replace placeholders before live use.', content:starterTemplateContent(kind)}))
  const byKind = Object.fromEntries(pack.templates.map((t: any) => [t.kind, t]))
  const patch = (kind: string, fields: any) => { byKind[kind].content = parseTemplateContent(kind as any, { ...byKind[kind].content, ...fields }) }
  patch('message',{text:'Hello {{inputs.name}}. **Atlas makes every interaction count.**',inputs:[{key:'name',label:'Visitor name',type:'string',required:true}]})
  patch('faq',{intro:'Atlas frequently asked questions',items:[{question:'Is this real checkout?',answer:'Only when demoMode is false and a payment connection is configured.'},{question:'Can I explore again?',answer:'Every journey returns to the hub.'}]})
  const products = pack.entityDefs.find((e: any) => e.key === 'atlas_products').records
  const categories = [...new Set(products.map((p: any) => p.category))].map((c: any) => ({id:c,name:c}))
  patch('cart',{currency:'ZAR',storeName:'Atlas Experiences',intro:'Create your own experience bundle.',checkoutLabel:'Review my basket',cartHint:'This is a demonstration catalog.',categories,products:products.map((p: any)=>({id:p.code,sku:p.code,name:p.name,description:'Fictional '+p.category+' experience',price:p.price,categoryId:p.category,image:'',stock:p.stock})),fees:[]})
  patch('receipt',{title:'Atlas order summary',intro:'Prepared for {{vars.displayName}}. This is a demonstration, not a tax invoice or proof of payment.',footer:'Thank you for exploring Atlas.',inputs:[]})
  patch('payment',{paymentConnectionId:'',payUrl:'',paymentAmount:'{{vars.cart.total}}',currencyCode:'ZAR',paymentItemName:'Atlas experience basket',paymentBuyerEmail:'{{vars.visitor.email}}',paymentBuyerName:'{{vars.displayName}}',inputs:[]})
  patch('email',{subject:'Your Atlas quote',html:'<h1>Your Atlas quote</h1><p>Hello {{vars.displayName}},</p><p>Your demonstration quote is R{{vars.quoteTotal}}.</p>',inputs:[]})
  for (const kind of ['document','agreement','certificate','checklist']) patch(kind,{format:'pdf',filename:'atlas-'+kind+'.pdf',title:'Atlas '+kind,intro:'Prepared for {{vars.displayName}}.',body:kind === 'document' ? 'Your chosen experience: {{inputs.service}}.\nDate: {{vars.booking_date}}\nTime: {{vars.booking_time}}\nGuests: {{vars.booking_people}}' : 'Demonstration only. This sample is not a signed contract or verified certificate.',footer:'Generated by FlowForge Atlas',fields:[{label:'Prepared for',value:'{{vars.displayName}}',as:'text'}],blocks:[],tableRowsSource:'',tableColumns:[],includeCart:false,inputs:kind === 'document' ? [{key:'service',label:'Experience',type:'string',required:true}] : []})
  patch('qr',{title:'Atlas demo reference',caption:'Scan to read a fictional reference. No payment is requested.',payload:'ATLAS-DEMO-2026',filename:'atlas-demo-qr.png',inputs:[]})
  patch('whatsapp',{phone:'12025550123',title:'WhatsApp contact card',subtitle:'Fictional example number. Replace before use.',message:'Hello Atlas',inputs:[]})
  patch('calendar',{title:'Atlas demo visit',description:'Fictional event. Adjust dates before adding.',location:'Atlas demo venue',start:'2027-01-15T08:00:00Z',end:'2027-01-15T09:00:00Z',timezone:'Africa/Johannesburg',inputs:[]})
  patch('social_share',{title:'Share the Atlas concept',text:'I explored the FlowForge Atlas capability showcase.',inputs:[]})
  patch('ticket',{title:'Atlas support request',intro:'Your request has been captured.',footer:'A live agent is contacted only when live handoff is enabled.',inputs:[]})
  // Starter templates carry realistic examples. Resolve their input slots to explicit demo values,
  // except the itinerary/message bindings above, which deliberately demonstrate template inputs.
  for (const template of pack.templates) {
    if (['document','message'].includes(template.kind)) continue
    let serialized = JSON.stringify(template.content)
    serialized = serialized.replace(/\{\{inputs\.[A-Za-z0-9_]+\}\}/g, 'Atlas demo')
    serialized = serialized.replaceAll('{{templates.hours_main.text}}', 'Monday to Saturday, 09:00-17:00')
    template.content = parseTemplateContent(template.kind,JSON.parse(serialized))
    if ('inputs' in template.content) template.content.inputs = []
  }
  pack.nodes.find((n: any)=>n.key === 'booking_document').config.templateBindings = {atlas_document:{service:'{{vars.booking_service}}'}}
  pack.nodes.find((n: any)=>n.key === 'gallery_message').config.templateBindings = {atlas_message:{name:'{{vars.displayName}}'}}
  pack.nodes.find((n: any)=>n.key === 'gallery_social').config.text = '{{templates.atlas_social_share.text}}'
  // Synthetic values only: omitting a global does not remove runtime/history output.
  for (const n of pack.nodes.filter((n: any)=>['try_credit_card','try_password','try_national_id'].includes(n.key))) n.config.outputVariable = ''
  writeFileSync(path,JSON.stringify(pack,null,2)+'\n')
  mkdirSync(resolve(dir,'media'),{recursive:true})
  for (const [name,color,label] of [['explore','#0369a1','EXPLORE'],['relax','#166534','RELAX'],['learn','#7e22ce','LEARN']]) writeFileSync(resolve(dir,'media','atlas-'+name+'.svg'),`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400" viewBox="0 0 640 400"><rect width="640" height="400" rx="32" fill="${color}"/><circle cx="510" cy="70" r="170" fill="white" opacity=".12"/><path d="M0 330L200 170 340 300 490 140 640 290V400H0Z" fill="white" opacity=".16"/><text x="48" y="215" fill="white" font-family="sans-serif" font-size="54" font-weight="700">${label}</text><text x="50" y="265" fill="white" font-family="sans-serif" font-size="20">ATLAS EXPERIENCES</text></svg>`)
}
const parsed = parseFlowExport(pack)
const nodeByKey = Object.fromEntries(parsed.nodes.map(n=>[n.key,n]))
const vars = Object.fromEntries(parsed.globals.map(g=>[g.key,g.default_value]))
describe('Atlas import pack',()=>{
  it('imports every template, entity, node and response type',()=>{
    expect(parsed.templates?.length).toBe(TEMPLATE_KINDS.length)
    expect(parsed.entityDefs?.length).toBe(8)
    expect(new Set(parsed.nodes.map(n=>n.type))).toEqual(new Set(flowNodeTypes))
    expect(new Set(parsed.nodes.filter(n=>n.type==='question').map(n=>n.config.answerType))).toEqual(new Set(questionAnswerTypes))
    for (const node of parsed.nodes) {
      if (node.type==='question') expect(questionConfigSchema.safeParse(node.config).success,node.key).toBe(true)
      if (node.type==='entity') expect(entityConfigSchema.safeParse(node.config).success,node.key).toBe(true)
    }
  })
  it('has one entry, valid jump targets, and no disconnected nodes',()=>{
    const incoming=new Set(parsed.edges.map(e=>e.target))
    expect(parsed.nodes.filter(n=>!incoming.has(n.id)).map(n=>n.key)).toEqual(['welcome'])
    const seen = new Set<string>();const queue=[nodeByKey.welcome.id]
    while(queue.length){const id=queue.shift()!;if(seen.has(id))continue;seen.add(id);queue.push(...parsed.edges.filter(e=>e.source===id).map(e=>e.target));const n=parsed.nodes.find(n=>n.id===id)!;if(n.type==='skip_to'){expect(nodeByKey[String(n.config.targetNodeKey)]).toBeDefined();queue.push(nodeByKey[String(n.config.targetNodeKey)].id)}}
    expect(seen.size).toBe(parsed.nodes.length)
  })
  it('guards every live connector in demo mode',()=>{
    for(const [gate,target] of [['payment_mode','demo_payment'],['agent_mode','demo_handoff'],['identity_mode','identity_demo'],...['http','database','email','integration','transfer'].map(k=>['gate_'+k,'preview_'+k])]){
      let state=createInitialPreviewState(parsed.nodes,parsed.edges,vars)
      state={...state,currentId:nodeByKey[gate].id,phase:{kind:'typing'}}
      state=tickPreview(state,parsed.nodes,parsed.edges)
      expect(state.currentId,gate).toBe(nodeByKey[target].id)
    }
  })
  it('routes all hub choices to the correct entry',()=>{
    for(const c of nodeByKey.hub_route.config.cases as any[]){let state=createInitialPreviewState(parsed.nodes,parsed.edges,{...vars,hub:c.match});state={...state,currentId:nodeByKey.hub_route.id,phase:{kind:'typing'}};state=tickPreview(state,parsed.nodes,parsed.edges);expect(state.currentId).toBe(parsed.edges.find(e=>e.source===nodeByKey.hub_route.id&&e.sourceHandle===c.id)?.target)}
  })
  it('finishes a joined-record loop and reaches the Excel table',()=>{
    let state=createInitialPreviewState(parsed.nodes,parsed.edges,{...vars,joinedProducts:[{name:'City',price:450,supplier:{name:'North',city:'Johannesburg'}},{name:'Coast',price:680,supplier:{name:'Coast',city:'Cape Town'}}]})
    state={...state,currentId:nodeByKey.supplier_loop.id,phase:{kind:'typing'}}
    for(let i=0;i<30 && state.currentId!==nodeByKey.scratch_create.id;i++) state=tickPreview(state,parsed.nodes,parsed.edges)
    expect(state.currentId).toBe(nodeByKey.scratch_create.id)
    expect(state.loopStack).toHaveLength(0)
    expect(state.messages.filter(message=>message.text?.includes(' - R'))).toHaveLength(2)
    expect(state.messages.some(message=>message.text?.includes('<<ff:table:'))).toBe(true)
  })
  it('still stops an automatic cycle that does not advance a loop',()=>{
    const cycleNodes=[{id:'a',key:'a',type:'message' as const,label:'a',config:{text:'a'},position:{x:0,y:0}},{id:'b',key:'b',type:'message' as const,label:'b',config:{text:'b'},position:{x:0,y:100}}]
    const cycleEdges=[{id:'ab',source:'a',target:'b'},{id:'ba',source:'b',target:'a'}]
    let state=createInitialPreviewState(cycleNodes,cycleEdges,{})
    state={...state,currentId:'a',phase:{kind:'typing'}}
    for(let i=0;i<5;i++)state=tickPreview(state,cycleNodes,cycleEdges)
    expect(state.phase.kind).toBe('finished')
    expect(state.messages.some(m=>m.text?.includes('Stopped:'))).toBe(true)
  })
  it('renders its rich gallery templates without unresolved expressions',()=>{
    const templates=Object.fromEntries(parsed.templates!.map(t=>[t.key,templateExprValue({id:t.key,...t})]))
    for(const key of ['gallery_message','gallery_hours','gallery_map','gallery_qr','gallery_whatsapp','gallery_social','gallery_certificate','gallery_agreement','gallery_checklist']){
      const n=nodeByKey[key];const result=interpolateTemplate(String(n.config.text),{vars:{...vars,displayName:'Explorer'},steps:{},templates,embedMedia:true,templateBindings:n.config.templateBindings as any})
      expect(result,key).not.toContain('{{')
      expect(result.length,key).toBeGreaterThan(10)
      if (key !== 'gallery_message') expect(parseChatSegments(result).some(segment=>segment.kind !== 'text'),key).toBe(true)
    }
  })
})
