export type InstanceRole = 'owner' | 'admin' | 'editor' | 'viewer'
export type VariableType = 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object'
export type VariableScope = 'global' | 'step'
export type ConnectionKind = 'http' | 'email' | 'payment'
export type ConnectionVisibility = 'private' | 'global' | 'shared'
export type IntegrationProvider =
  | 'microsoft_onedrive'
  | 'google_drive'
  | 'dropbox'
  | 'box'
  | 'sharepoint'
  | 'slack'
  | 'microsoft_teams'
  | 'google_sheets'
  | 'notion'
  | 's3'
  | 'custom'
export type IntegrationStatus = 'disconnected' | 'connected' | 'error'
export type FlowNodeType =
  | 'message'
  | 'question'
  | 'http'
  | 'email'
  | 'integration'
  | 'condition'
  | 'loop'
  | 'set_variable'
  | 'operation'
  | 'entity'
  | 'end'

export type EntityKind = 'static' | 'dynamic'
